In [2]:
import numpy as np

# Exercicio 1

Faça um programa que crie dois NumPy Arrays unidimensionais de tamanho 8:

- O primeiro deve ser preenchido automaticamente apenas com o número **1**.

- O segundo deve ser formado por **números inteiros digitados pelo usuário**, no intervalo de 0 a 9.

Em seguida, o programa deve:

1. Somar os dois Arrays e armazenar o resultado em um terceiro Array.

2. Calcular a soma de todos os elementos do Array resultante.

3. Remodele o array do item 1 segundo a seguinte regra:

    - Se a soma for **maior ou igual a 40**, remodelar o Array para uma matriz de tamanho **4 × 2** (4 linhas e 2 colunas).

    - Caso contrário, remodelar o Array para uma matriz de tamanho **2 × 4** (2 linhas e 4 colunas).

 
### Entrada
A entrada consiste de uma única linha, com 8 números inteiros.

### Saída
Na saĩda, o programa deve mostrar os resultados dos itens 1, 2 e 3, como no exemplo abaixo.

| Exemplo de Entrada | Exemplo de Saída |
|--------------------|------------------|
| 5 2 0 3 4 1 7 6    | Array resultante da soma: <br>[6 3 1 4 5 2 8 7]<br> <br>Soma de todos os elementos: <br>36<br> <br>Matriz (2 x 4):<br>[[6 3 1 4]<br> [5 2 8 7]] |

In [6]:
first_array = np.array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int)
second_array = np.array(input().split(), dtype=int)

third_array = np.add(first_array, second_array)
sum_elements = np.sum(third_array)
print (f'Array resultante da soma: \n {third_array}')
print('\n')
print(f'Soma de todos os elementos: \n {sum_elements}')
print('\n')

if sum_elements < 40:
    print("Matriz (2 x 4):")
    print(third_array.reshape(2, 4))
else:
    print("Matriz (4 x 2):")
    print(third_array.reshape(4, 2))

Array resultante da soma: 
 [3 3 3 3 3 3 3 3]


Soma de todos os elementos: 
 24


Matriz (2 x 4):
[[3 3 3 3]
 [3 3 3 3]]


# Exercicio 2

Faça um programa que leia 4 números inteiros N1, N2, N3 e N4.

Depois o programa deve criar 2 arrays: 

o primeiro com os números pares no intervalo [N1, N2]
o segundo com os números pares no intervalo [N3, N4]
Finalmente, o programa deve concatenar estes 2 arrays e mostrar o array resultante em ordem crescente.

Observação: N1 não será necessariamente menor que N2, e nem N3 será necessariamente menor que N4. Inclua testes no seu programa para que ele funcione adequadamente.

### Entrada
A entrada consiste de uma única linha, com 4 números inteiros, correspondentes a N1, N2, N3 e N4.

 
### Saída
Na saĩda, o programa deve mostrar o array resultante da concatenação dos 2 arrays, em ordem crescente.

| Exemplos de Entrada | Exemplos de Saída |
|---------------------|-------------------|
| 2 4 9 5             | [2, 4, 6, 8]      |

In [15]:
# Ler 4 numeros inteiros
numbers = input("Digite 4 numeros inteiros: ").split()

# Verificar se o primeiro é maior que o segundo
if int(numbers[0]) > int(numbers[1]):
    numbers[0], numbers[1] = numbers[1], numbers[0]
if int(numbers[2]) > int(numbers[3]):
    numbers[2], numbers[3] = numbers[3], numbers[2]
    
# Criar os arrays com os numeros pares
first_array = []
second_array = []

for i in range(int(numbers[0]), int(numbers[1]) + 1):
    if i % 2 == 0:
        first_array.append(i)
        

for j in range(int(numbers[2]), int(numbers[3]) + 1):
    if j % 2 == 0:
        second_array.append(j)

# Concatenar os arrays e ordenar
concated_array = np.concatenate((
    np.array(first_array, dtype=int), 
    np.array(second_array, dtype=int)
))

print(f"{np.sort(concated_array)}")

[2 4 6 8]


# Exercicio 3

Vamos fazer um mini campo minado

Faça um programa que crie um numpy array 2x2 formado apenas por 0s.

Depois o programa deve ler uma posição desta matriz (linha e coluna), e inserir o número 1 nesta posição

Finalmente, o programa deve ler mais 3 posições, correspondentes às jogadas do usuário.

Se estas 3 posições corresponderem a posições em que o número 1 não se encontra, mostre a mensagem: “Congratulations! You beat the game!”

Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem “Game Over! Try Again!”

### Entrada
A entrada consiste de várias linhas:

a primeira linha contém 2 inteiros, que correspondem à posição onde o 1 vai ser inserido
as 3 linhas a seguir contêm 2 inteiros cada, que correspondem às jogadas.

### Saída
Na saĩda, o programa deve mostrar as mensagens solicitadas, de acordo com o resultado do jogo.

| Exemplos de Entrada | Exemplos de Saída |
|---------------------|-------------------|
| 0 0<br>0 1<br>1 0<br>1 1 | Congratulations! You beat the game! |
| 0 0<br>0 1<br>1 0<br>1 0 | Game Over! Try Again! |


In [ ]:
# Generate a numpy array 2x2 with zeros
random_matrix = np.zeros((2, 2))

# Read the matriz position and insert the number 1
line, column = input(i for _ in range(2)).split()

random_matrix[int(line), int(column)] = 1

# Read more 3 positions and present results
for _ in range(3):
    line, column = input(i for _ in range(2)).split()

    if random_matrix[int(line), int(column)] == 1:
        print("Game Over! Try Again!")
        break

    random_matrix[int(line), int(column)] = 1
else:
    print("Congratulations! You beat the game!")

Game Over! Try Again!


# Exercicio 4

Faça um programa que:

Leia uma matriz do usuário, linha por linha. Cada linha contém números inteiros separados por espaço.

1. Crie um NumPy array com os valores informados.

2. Extraia o número de linhas e colunas da matriz usando o atributo shape.

3. Multiplique o número de linhas pelo número de colunas para obter o total de elementos da matriz.

4. Informe se a matriz poderia ser convertida em um vetor unidimensional com número par ou ímpar de elementos.

### Entrada

- A primeira linha da entrada terá um único inteiro L, que corresponde à quantidade de linhas da matriz.

- Seguem-se L linhas, que correspondem aos elementos das linhas da matriz, com números separados por espaço.

### Saída

Na saída o programa deve mostrar:

- A quantidade de linhas e colunas da matriz.

- Uma mensagem indicando se o vetor resultante teria número par ou ímpar de elementos.

| Exemplos de Entrada | Exemplos de Saída |
|---------------------|-------------------|
| 2<br>1 2 3<br>4 5 6 | 2 linhas <br><br> 3 colunas<br><br>O vetor resultante teria número par de elementos. |

In [ ]:
# Read the number of lines of the matriz
matriz_lines = int(input())

# Read the matriz values
random_matrix = np.array([input().split() for _ in range(matriz_lines)], dtype=int)

print(f"{random_matrix.shape[0]} linhas \n")
print(f"{random_matrix.shape[1]} colunas")

total_elements = random_matrix.size
parity = "par" if total_elements % 2 == 0 else "ímpar"
print(f"O vetor resultante teria um número {parity} de elementos")

2 linhas 

3 colunas
O vetor resultante teria um número par de elementos


# Exercicio 5

Faça um programa que:

1. Leia um número inteiro do usuário que será usado como seed para gerar números aleatórios.

2. Crie uma matriz 4x4 formada por números aleatórios inteiros entre 1 e 50 usando o NumPy.

3. Mostre:

    a. A média de cada linha e de cada coluna da matriz gerada.
    
    b. O maior valor entre as médias das linhas e o maior valor entre as médias das colunas.
    
    c. A quantidade de aparições de cada número presente na matriz. Em seguida, mostre apenas os números que aparecem exatamente 2 vezes.

### Entrada

- Um único inteiro: a semente (seed) para gerar os números aleatórios.

### Saída

- Médias de cada linha e coluna.

- Maior valor das médias das linhas e das colunas.

- Frequência de cada número presente na matriz.

- Números que aparecem exatamente 2 vezes.

| Exemplo de Entrada | Exemplo de Saída |
|--------------------|------------------|
| 10 | Média das linhas: [28.5 19.25 23.0 28.75] <br> Média das colunas: [24.5 19.5 25.25 30.25] <br> Maior média das linhas: 28.75 <br> Maior média das colunas: 30.25 <br> Contagem de números: {4: 1, 9: 1, 13: 1, 29: 1, 5: 1, 33: 1, 24: 1, 14: 1, 1: 1, 18: 1, 20: 1, 33: 1, 31: 1, 28: 1, 12: 1, 30: 1} <br> Números que aparecem 2 vezes: [33] |

In [19]:
# Read a seed number and generate random numbers
seed = int(input())

# Generate the matriz with random numbers between 1 and 50
np.random.seed(seed)
random_matrix = np.random.randint(1, 51, size=(4, 4))

# Calculate the averages of lines and columns
line_averages = random_matrix.mean(axis=1)
column_averages = random_matrix.mean(axis=0)

# Find the maximum average in lines and columns
max_lines = line_averages.max()
max_column = column_averages.max()

# Count occurrences of each number in the matrix
matrix_values, value_occurrences = np.unique(random_matrix, return_counts=True)

# get numbers that appear exactly 2 times
show_2 = matrix_values[value_occurrences == 2]

# Show Results
print(f"Média das linhas: {line_averages}")
print(f"Média das colunas: {column_averages}")
print(f"Maior média das linhas: {max_lines}")
print(f"Maior média das colunas: {max_column}")
print(f'Valores: {matrix_values}')
print(f'Contagens: {value_occurrences}')
print(f"Números que aparecem 2 vezes: {show_2}")

Média das linhas: [16.   33.75 34.5  23.75]
Média das colunas: [29.75 24.25 33.75 20.25]
Maior média das linhas: 34.5
Maior média das colunas: 33.75
Valores: [ 1  9 10 16 26 29 30 37 41 43 49 50]
Contagens: [2 1 2 1 1 1 2 1 1 1 1 2]
Números que aparecem 2 vezes: [ 1 10 30 50]
